hero_image: images/create-your-own-world.png
title: Erstelle deine eigene Welt
description: Lerne, wie du dein eigenes Open-World Abenteuerspiel erstellen kannst.
original_url: https://codeclubprojects.org/en-GB/scratch/create-your-own-world
theme: orange
duration: 2
listed: false
ingredient: false
copyedit: false
curriculum: 2, design-0, programming-2, phys-comp-0, manufacture-0, community-0
interests: games
technologies: scratch
site_areas: projects
hardware: ''
software: scratch
version: 4
last_tested: 2017-01-01
steps: 
- title: Einf端hrung
- title: Programmiere deinen Spieler
- title: Programmiere deine Welt
- title: Schilder
- title: Leute
- title: M端nzen sammeln
- title: T端ren und Schl端ssel