---
hero_image: images/create-your-own-world.png
title: Kreiraj sopstveni svijet
description: Nauči kako da napraviš sopstvenu igru avanture u otvorenom svijetu.
original_url: https://codeclubprojects.org/en-GB/scratch/create-your-own-world
theme: orange
duration: 2
listed: false
ingredient: false
copyedit: false
curriculum: 2, design-0, programming-2, phys-comp-0, manufacture-0, community-0
interests: games
technologies: scratch
site_areas: projects
hardware: ''
software: scratch
version: 4
last_tested: 2017-01-01
steps:
  - title: Uvod
  - title: Šta će ti biti potrebno
  - title: Pomjeranje lika igrača
  - title: Čvrsti zidovi
  - title: Programiranje tvog svijeta
  - title: Znakovi
  - title: 'Izazov: blago!'
  - title: Osobe
  - title: 'Izazov: neprijatelji'
  - title: Sakupljanje novčića
  - title: Vrata i ključevi
  - title: 'Izazov: proširi svoj svijet'
